# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadcell_third.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_loadcell_third(object):
    def setupUi(self, loadcell_third):
        loadcell_third.setObjectName("loadcell_third")
        loadcell_third.resize(523, 394)
        self.centralwidget = QtWidgets.QWidget(loadcell_third)
        self.centralwidget.setObjectName("centralwidget")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(20, 10, 131, 61))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("../AEL form/AEL-removebg-preview.png"))
        self.label_logo.setObjectName("label_logo")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(170, 20, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(28)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 140, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 190, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.text_loadcell1_value = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_loadcell1_value.setGeometry(QtCore.QRect(310, 140, 111, 41))
        self.text_loadcell1_value.setObjectName("text_loadcell1_value")
        self.text_loadcell2_value = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_loadcell2_value.setGeometry(QtCore.QRect(310, 190, 111, 41))
        self.text_loadcell2_value.setObjectName("text_loadcell2_value")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(130, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.text_counterweight = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_counterweight.setGeometry(QtCore.QRect(310, 90, 111, 41))
        self.text_counterweight.setObjectName("text_counterweight")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(430, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_next.setGeometry(QtCore.QRect(270, 300, 159, 44))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(20)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(100, 300, 159, 44))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(20)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_home = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_home.setGeometry(QtCore.QRect(10, 300, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(14)
        self.pushButton_home.setFont(font)
        self.pushButton_home.setObjectName("pushButton_home")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 250, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        loadcell_third.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(loadcell_third)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 21))
        self.menubar.setObjectName("menubar")
        loadcell_third.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(loadcell_third)
        self.statusbar.setObjectName("statusbar")
        loadcell_third.setStatusBar(self.statusbar)

        self.retranslateUi(loadcell_third)
        QtCore.QMetaObject.connectSlotsByName(loadcell_third)

    def retranslateUi(self, loadcell_third):
        _translate = QtCore.QCoreApplication.translate
        loadcell_third.setWindowTitle(_translate("loadcell_third", "MainWindow"))
        self.label_title.setText(_translate("loadcell_third", "称重传感器校准模式"))
        self.label_5.setText(_translate("loadcell_third", "称重传感器#1值 ："))
        self.label_6.setText(_translate("loadcell_third", "称重传感器#2值 ："))
        self.label_7.setText(_translate("loadcell_third", "标准重量值 ："))
        self.label_8.setText(_translate("loadcell_third", "kg"))
        self.pushButton_next.setText(_translate("loadcell_third", "下一步"))
        self.pushButton_back.setText(_translate("loadcell_third", "上一步"))
        self.pushButton_home.setText(_translate("loadcell_third", "主页"))
        self.label_9.setText(_translate("loadcell_third", "称重传感器值稳定下来后请按“下一步”完成校准"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loadcell_third = QtWidgets.QMainWindow()
    ui = Ui_loadcell_third()
    ui.setupUi(loadcell_third)
    loadcell_third.show()
    sys.exit(app.exec_())

