# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operation.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 230, 221, 251))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.start_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.start_pushButton.setGeometry(QtCore.QRect(40, 40, 141, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setObjectName("start_pushButton")
        self.stop_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.stop_pushButton.setGeometry(QtCore.QRect(40, 150, 141, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.stop_pushButton.setFont(font)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 350, 311, 211))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.log_textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.log_textBrowser.setGeometry(QtCore.QRect(10, 30, 291, 171))
        self.log_textBrowser.setObjectName("log_textBrowser")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 80, 311, 131))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(16)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.temp_LCDNumber = QtWidgets.QLCDNumber(self.groupBox_3)
        self.temp_LCDNumber.setGeometry(QtCore.QRect(110, 30, 71, 31))
        self.temp_LCDNumber.setObjectName("temp_LCDNumber")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(190, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.humi_textBrowser = QtWidgets.QLCDNumber(self.groupBox_3)
        self.humi_textBrowser.setGeometry(QtCore.QRect(110, 80, 71, 31))
        self.humi_textBrowser.setObjectName("humi_textBrowser")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(190, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 220, 311, 121))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(16)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.doorhome_greenoff = QtWidgets.QLabel(self.groupBox_4)
        self.doorhome_greenoff.setGeometry(QtCore.QRect(40, 70, 41, 41))
        self.doorhome_greenoff.setText("")
        self.doorhome_greenoff.setPixmap(QtGui.QPixmap("greenlampoff.bmp"))
        self.doorhome_greenoff.setScaledContents(True)
        self.doorhome_greenoff.setObjectName("doorhome_greenoff")
        self.doorhome_greenon = QtWidgets.QLabel(self.groupBox_4)
        self.doorhome_greenon.setGeometry(QtCore.QRect(40, 70, 41, 41))
        self.doorhome_greenon.setText("")
        self.doorhome_greenon.setPixmap(QtGui.QPixmap("greenlamp.bmp"))
        self.doorhome_greenon.setScaledContents(True)
        self.doorhome_greenon.setObjectName("doorhome_greenon")
        self.doorup_greenon = QtWidgets.QLabel(self.groupBox_4)
        self.doorup_greenon.setGeometry(QtCore.QRect(140, 70, 41, 41))
        self.doorup_greenon.setText("")
        self.doorup_greenon.setPixmap(QtGui.QPixmap("greenlamp.bmp"))
        self.doorup_greenon.setScaledContents(True)
        self.doorup_greenon.setObjectName("doorup_greenon")
        self.doorup_greenoff = QtWidgets.QLabel(self.groupBox_4)
        self.doorup_greenoff.setGeometry(QtCore.QRect(140, 70, 41, 41))
        self.doorup_greenoff.setText("")
        self.doorup_greenoff.setPixmap(QtGui.QPixmap("greenlampoff.bmp"))
        self.doorup_greenoff.setScaledContents(True)
        self.doorup_greenoff.setObjectName("doorup_greenoff")
        self.doorrot_greenoff = QtWidgets.QLabel(self.groupBox_4)
        self.doorrot_greenoff.setGeometry(QtCore.QRect(240, 70, 41, 41))
        self.doorrot_greenoff.setText("")
        self.doorrot_greenoff.setPixmap(QtGui.QPixmap("greenlampoff.bmp"))
        self.doorrot_greenoff.setScaledContents(True)
        self.doorrot_greenoff.setObjectName("doorrot_greenoff")
        self.doorrot_greenon = QtWidgets.QLabel(self.groupBox_4)
        self.doorrot_greenon.setGeometry(QtCore.QRect(240, 70, 41, 41))
        self.doorrot_greenon.setText("")
        self.doorrot_greenon.setPixmap(QtGui.QPixmap("greenlamp.bmp"))
        self.doorrot_greenon.setScaledContents(True)
        self.doorrot_greenon.setObjectName("doorrot_greenon")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(30, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(130, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(230, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.doorhome_greenon.raise_()
        self.doorhome_greenoff.raise_()
        self.doorup_greenon.raise_()
        self.doorup_greenoff.raise_()
        self.doorrot_greenon.raise_()
        self.doorrot_greenoff.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 490, 91, 62))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ver = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ver.setFont(font)
        self.label_ver.setObjectName("label_ver")
        self.verticalLayout_2.addWidget(self.label_ver)
        self.label_devdate = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_devdate.setFont(font)
        self.label_devdate.setObjectName("label_devdate")
        self.verticalLayout_2.addWidget(self.label_devdate)
        self.label_devperson = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_devperson.setFont(font)
        self.label_devperson.setObjectName("label_devperson")
        self.verticalLayout_2.addWidget(self.label_devperson)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 80, 221, 131))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(16)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.model_textBrowser = QtWidgets.QTextBrowser(self.groupBox_5)
        self.model_textBrowser.setGeometry(QtCore.QRect(60, 30, 151, 41))
        self.model_textBrowser.setObjectName("model_textBrowser")
        self.serial_textBrowser = QtWidgets.QTextBrowser(self.groupBox_5)
        self.serial_textBrowser.setGeometry(QtCore.QRect(60, 80, 151, 41))
        self.serial_textBrowser.setObjectName("serial_textBrowser")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(10, 10, 131, 61))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("AEL-removebg-preview.png"))
        self.label_logo.setObjectName("label_logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 616, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ARCS 户外投放口 运行模式"))
        self.groupBox.setTitle(_translate("MainWindow", "程序执行"))
        self.start_pushButton.setText(_translate("MainWindow", "开启"))
        self.stop_pushButton.setText(_translate("MainWindow", "停止"))
        self.groupBox_2.setTitle(_translate("MainWindow", "运作记录"))
        self.groupBox_3.setTitle(_translate("MainWindow", "状态信息"))
        self.label_2.setText(_translate("MainWindow", "电箱温度 ："))
        self.label_3.setText(_translate("MainWindow", "度"))
        self.label_4.setText(_translate("MainWindow", "电箱湿度 ："))
        self.label_5.setText(_translate("MainWindow", "%"))
        self.groupBox_4.setTitle(_translate("MainWindow", "投放门状态"))
        self.label_6.setText(_translate("MainWindow", "盖门原位"))
        self.label_7.setText(_translate("MainWindow", "盖门顶起"))
        self.label_8.setText(_translate("MainWindow", "盖门打开"))
        self.label_ver.setText(_translate("MainWindow", "Ver.1 "))
        self.label_devdate.setText(_translate("MainWindow", "2022年5月20日"))
        self.label_devperson.setText(_translate("MainWindow", "Paul Kang"))
        self.groupBox_5.setTitle(_translate("MainWindow", "设备信息"))
        self.label_11.setText(_translate("MainWindow", "型号"))
        self.label_12.setText(_translate("MainWindow", "编号"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

